/* Palace Bingo — host credentials.
 *
 * Generated by set-password.html. There is no username or password in this file: only a
 * random salt and a token that the right credentials can decrypt. Commit it as it is.
 */

export const CREDENTIALS = {
  v: 1,
  iterations: 310000,
  salt: "A0pehtfKeqN9CywrdjOY3A==",
  iv: "fvdDEu/DPsb8V7E1",
  token: "/FvZ0bTfXzoTwQlbZkFMmQDUJl07T00sJhjzz5ZabniCKEoq"
};
