/* Palace Bingo — host credentials.
 *
 * Generated by set-password.html. There is no username or password in this file: only a
 * random salt and a token that the right credentials can decrypt. Commit it as it is.
 */

export const CREDENTIALS = {
  v: 1,
  iterations: 310000,
  salt: "9+aHS2C91Fki6cEEW47Z2A==",
  iv: "koLBd/jUEZqJQ0qT",
  token: "q4k3fsljM5ElDMCuAx8EygpJJ2xiSLcT2aZogJCMGF+b+W9n"
};
