/* Palace Bingo — host credentials.
 *
 * Generated by set-password.html. There is no username or password in this file: only a
 * random salt and a token that the right credentials can decrypt. Commit it as it is.
 */

export const CREDENTIALS = {
  v: 1,
  iterations: 310000,
  salt: "XeUkkmfjpfmfHpdCbdHBDA==",
  iv: "ZhYlCtP5LISdAj9t",
  token: "JiVdC5+sfgkQy/t88yZ9esmCVKYVwfedCnWab/GAZI8vkIYq"
};
