/* Marquee Event System — who can open the console.
 * Generated by the console's Users pane. No name or password in here: a salt and a
 * token that only the right password can decrypt. Commit it as it is.
 */

export const USERS = [
  {
    "v": 1,
    "name": "admin",
    "role": "admin",
    "iterations": 310000,
    "salt": "fqpYLse12xtA/nsIyrDYHQ==",
    "iv": "mwYXJJPjQQoL3fTU",
    "token": "6qazA+ki8murgFFLO1W3wI028JdItT+MAzXDuumGIGSNNGw="
  },
  {
    "v": 1,
    "name": "Tom",
    "role": "admin",
    "iterations": 310000,
    "salt": "7wcQTTiLX8hTFUJ7dQi+Vg==",
    "iv": "0MRz4eUgdQk+pli9",
    "token": "OLYcA2wuZex53c03SGijqpIFDK+jRurrMdTnAElen1JXTXg="
  },
  {
    "v": 1,
    "name": "Caller",
    "role": "caller",
    "iterations": 310000,
    "salt": "jcGNwShxtQ1Wvwp4WYcQuA==",
    "iv": "v6aWsmd7jePv0q8+",
    "token": "ThCDBIPl+IFxmn8OIA5SW7dIuRmFKWMOB6bhIm2YrLGYTII="
  },
  {
    "v": 1,
    "name": "Checker",
    "role": "checker",
    "iterations": 310000,
    "salt": "Hra3r+PObFEnJLDMTo3Mkw==",
    "iv": "vIGjdiQH/3BVJEDY",
    "token": "2lKy7CSXofm7RXosa351NwasrCl/jIDe8iGmPdPg9qjs7H4="
  }
];

export const CREDENTIALS = null;
