/* Marquee Event System — operator credentials.
 * Generated by set-password.html. No username or password in here: a random salt and a
 * token the right credentials can decrypt. Commit it as it is.
 */

export const CREDENTIALS = {
  v: 1,
  iterations: 310000,
  salt: "1feo7U7m7/ug60Z1U+nsNw==",
  iv: "IOM+oYIhK3rEHk1l",
  token: "UUZtD6BMgGU4+fBJPBM6An44SFwa1bf5pOk6MfiT9RxYtJM="
};
