/* Marquee Event System — who can open the console.
 * Generated by set-password.html. No name or password in here: a salt and a token
 * that only the right password can decrypt. Commit it as it is.
 *
 * The admin can add more operators from the console's Users pane and download a
 * new copy of this file. Roles: "admin", "caller", "checker".
 */

export const USERS = [
  {
    v: 1,
    name: "admin",
    role: "admin",
    iterations: 310000,
    salt: "fqpYLse12xtA/nsIyrDYHQ==",
    iv: "mwYXJJPjQQoL3fTU",
    token: "6qazA+ki8murgFFLO1W3wI028JdItT+MAzXDuumGIGSNNGw="
  }
];

export const CREDENTIALS = null;
